branding:
  color: green
  icon: play
description:
  🚀 Trigger other workflows, display a link, and optionally wait for the
  result.
name: Workflow Dispatch Plus
inputs:
  inputs:
    description: JSON object of inputs
    default: "{}"
  marker-input:
    description: Name of input for this workflow's URL
  repo:
    default: ${{ github.repository }}
    description: Repository owner and name
  ref:
    default: ${{ github.ref }}
    description: Ref
  token:
    default: ${{ github.token }}
    description:
      Personal access token, see
      https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
  wait:
    default: "false"
    description: Whether to wait for
  workflow:
    description: Workflow file path
    required: true
outputs:
  conclusion:
    description: Conclusion of workflow run
  run_id:
    description: Workflow run ID
runs:
  using: node16
  main: workflow-dispatch/dist/main.js
